#!/usr/bin/env python

import requirements

from twisted.internet import reactor

from tp.server.model import DatabaseManager

DatabaseManager()

from tp.server.logging import Logger
from tp.server.server import ThousandParsecServerFactory

class Configuration( object ):
	log_level		= 'info'
	log_drop_time	= False
	log_drop_system	= False
	tcp_port		= 6923
	tls_port		= 6924
	listen_tls		= False
	database		= 'sqlite:///tp.db'

def main():
	configuration = Configuration()

	logger	= Logger()
	factory	= ThousandParsecServerFactory()

	try:
		logger.configure( configuration )
		factory.configure( configuration )
		DatabaseManager().configure( configuration )
	except Exception, ex:
		raise SystemExit( '\033[31;1mConfiguration error:\033[0m %s' % ex )

	logger.start()
	factory.start()
	reactor.run()

if __name__ == "__main__":
	main()
