#!/usr/bin/env python

import sys, requirements

sys.path.insert(0, 'tests')

from twisted.internet import reactor

from tp.server.logging import Logger
from tp.server.server import ThousandParsecServerFactory
from tp.server.model import DatabaseManager

DatabaseManager()

from configuration import CLIConfigurator, ConfigurationError
from configuration import LoggerConfiguration, ThousandParsecServerConfiguration, DatabaseConfiguration

def main():
	logger	= Logger()
	factory	= ThousandParsecServerFactory()

	configurator = CLIConfigurator( "Thousand Parsec Server" )
	configurator.registerComponent( logger, LoggerConfiguration() )
	configurator.registerComponent( factory, ThousandParsecServerConfiguration() )
	configurator.registerComponent( DatabaseManager(), DatabaseConfiguration() )

	try:
		configurator.configParse()
		configurator.configCommit()
	except ConfigurationError, ex:
		configurator.help()

		raise SystemExit( '\033[31;1mConfiguration error:\033[0m %s' % ex )

	logger.start()
	factory.start()
	reactor.run()

if __name__ == "__main__":
	main()
