#!/usr/bin/env python

import requirements

from twisted.internet import reactor

from tp.server.configuration import CLIConfigurator, ConfigurationError
from tp.server.server import ThousandParsecServerFactory, ThousandParsecServerConfiguration
from tp.server.logging import Logger, LoggerConfiguration

def main():
	logger	= Logger()
	factory	= ThousandParsecServerFactory()

	configurator = CLIConfigurator( "Thousand Parsec Server" )
	configurator.registerComponent( logger, LoggerConfiguration() )
	configurator.registerComponent( factory, ThousandParsecServerConfiguration() )

	try:
		configurator.configParse()
		configurator.configCommit()
	except ConfigurationError, ex:
		configurator.help()

		raise SystemExit( '\033[31;1mConfiguration error:\033[0m %s' % ex )

	logger.start()
	factory.start()
	reactor.run()

if __name__ == "__main__":
	main()
